export const POSTS_SUCCESS = Symbol('POSTS_SUCCESS');

export const SINGLE_POST_SUCCESS = Symbol('SINGLE_POST_SUCCESS');

export const CREATE_POST_SUCCESS = Symbol('CREATE_POST_SUCCESS');

export const UPDATE_POST_SUCCESS = Symbol('UPDATE_POST_SUCCESS');

export const DELETE_POST_SUCCESS = Symbol('DELETE_POST_SUCCESS');

export const CREATE_COMMENT_SUCCESS = Symbol('CREATE_COMMENT_SUCCESS');

