export const POSTS_REQUEST = Symbol('POSTS_REQUEST');
export const POSTS_SUCCESS = Symbol('POSTS_SUCCESS');
export const POSTS_FAILURE = Symbol('POSTS_FAILURE');

export const SINGLE_POST_REQUEST = Symbol('SINGLE_POST_REQUEST');
export const SINGLE_POST_SUCCESS = Symbol('SINGLE_POST_SUCCESS');
export const SINGLE_POST_FAILURE = Symbol('SINGLE_POST_FAILURE');

export const CREATE_POST_REQUEST = Symbol('CREATE_POST_REQUEST');
export const CREATE_POST_SUCCESS = Symbol('CREATE_POST_SUCCESS');
export const CREATE_POST_FAILURE = Symbol('CREATE_POST_FAILURE');

export const UPDATE_POST_REQUEST = Symbol('UPDATE_POST_REQUEST');
export const UPDATE_POST_SUCCESS = Symbol('UPDATE_POST_SUCCESS');
export const UPDATE_POST_FAILURE = Symbol('UPDATE_POST_FAILURE');

export const DELETE_POST_REQUEST = Symbol('DELETE_POST_REQUEST');
export const DELETE_POST_SUCCESS = Symbol('DELETE_POST_SUCCESS');
export const DELETE_POST_FAILURE = Symbol('DELETE_POST_FAILURE');

export const CREATE_COMMENT_REQUEST = Symbol('CREATE_COMMENT_REQUEST');
export const CREATE_COMMENT_SUCCESS = Symbol('CREATE_COMMENT_SUCCESS');
export const CREATE_COMMENT_FAILURE = Symbol('CREATE_COMMENT_FAILURE');

